* server-src/reporter.c: Fix to make the mailto parameter in amanda.conf optional. Added two more commandline options -i & -Maddress. * server-src/amcheck.c: Fix to make the mailto parameter in amanda.conf optional. * man/xml-source/amreport.8.xml: Modified to document the -i & -Maddress commandline parameters * docs/amreport.8.txt: Modified to document the -i & -Maddress commandline parameters * changer-src/chg-scsi.c: Fix to make the mailto parameter in amanda.conf optional. * changer-src/chg-scsi-chio.c: Fix to make the mailto parameter in amanda.conf optional. * tape-src/output-tape.c: Do a more thourough check to ensure that we actually got a tape device, before proceeding to use it. * changer-src/chg-disk.sh.in: Check that the virtual device is a directory with proper permissions. * server-src/changer.c: Do the right thing (failure) if there is a problem with the changer. * recover-src/uscan.l: Accept setdate of the form yyyy-MM-dd-hh-mm in addition to yyyy-MM-dd-hh-mm-ss. * man/xml-source/amrecover.8.xml: Document this change.

diff --git a/changer-src/chg-disk.sh.in b/changer-src/chg-disk.sh.in
--- a/changer-src/chg-disk.sh.in
+++ b/changer-src/chg-disk.sh.in
@@ -86,25 +86,36 @@ isinteger() {
 	expr "$1" : '[0-9][0-9]*$' > /dev/null 2>&1
 }
 
+# Need rwx access to the virtual tape itself.
+if ! test -d $SLOTDIR; then
+    echo "Virtual-tape directory $SLOTDIR does not exist." 1>&2
+    exit 2
+fi
+if ! test -w $SLOTDIR; then
+    echo "Virtual-tape directory $SLOTDIR is not writable." 1>&2
+    exit 2
+fi
+
+
 # need rwx access to directory of changer file
 CHANGERFILE=`amgetconf$SUF changerfile`
 CFDir=`dirname ${CHANGERFILE}`
 [ -d ${CFDir} -a -r ${CFDir} -a -w ${CFDir} -a -x ${CFDir} ] ||
-	{ echo "$MYNAME: need 'rwx' access to '$CFDir'" ; exit 2 ; }
+	{ echo "$MYNAME: need 'rwx' access to '$CFDir'" 1>&2 ; exit 2 ; }
 
 # check or create changer metadata files
 ACCESSFILE=$CHANGERFILE-access
 [ -f $ACCESSFILE -a -r $ACCESSFILE -a -w $ACCESSFILE ] ||
 	echo 0 > $ACCESSFILE ||
-	{ echo "$MYNAME: could not access or create '$ACCESSFILE'" ; exit 2 ; }
+	{ echo "$MYNAME: could not access or create '$ACCESSFILE'" 1>&2 ; exit 2 ; }
 CLEANFILE=$CHANGERFILE-clean
 [ -f $CLEANFILE -a -r $CLEANFILE -a -w $CLEANFILE ] ||
 	echo 0 > $CLEANFILE ||
-	{ echo "$MYNAME: could not access or create '$CLEANFILE'" ; exit 2 ; }
+	{ echo "$MYNAME: could not access or create '$CLEANFILE'" 1>&2 ; exit 2 ; }
 SLOTFILE=$CHANGERFILE-slot
 [ -f $SLOTFILE -a -r $SLOTFILE -a -w $SLOTFILE ] ||
 	echo 0 > $SLOTFILE ||
-	{ echo "$MYNAME: could not access or create '$SLOTFILE'" ; exit 2 ; }
+	{ echo "$MYNAME: could not access or create '$SLOTFILE'" 1>&2 ; exit 2 ; }
 
 # read and check metadata
 ACCESSCOUNT=`cat $ACCESSFILE`
