Update amrmtape, amcheckdb, amfreetapes, and amtoc to use the tapelist option in amanda.conf if it's set.
Remove the references to my() in amtoc to keep perl4 compatibility.  If we
really want to move to perl5 for amtoc, then I'd add -w and use strict.

diff --git a/server-src/amcheckdb.sh.in b/server-src/amcheckdb.sh.in
--- a/server-src/amcheckdb.sh.in
+++ b/server-src/amcheckdb.sh.in
@@ -6,7 +6,12 @@
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 sbindir=@sbindir@
-CONFIG_DIR=@CONFIG_DIR@
+libexecdir=@libexecdir@
+
+ConfigDir=@CONFIG_DIR@
+
+PATH=$libexecdir:$sbindir:/usr/bin:/bin:/usr/sbin:/sbin:/usr/ucb
+export PATH
 
 USE_VERSION_SUFFIXES="@USE_VERSION_SUFFIXES@"
 if test "$USE_VERSION_SUFFIXES" = "yes"; then
@@ -15,24 +20,53 @@ else
 	SUF=
 fi
 
-CONFIG=$1
-[ "$CONFIG" = "" ] \
-	&& echo "usage: $0 <config>" >&2 \
+Program=`basename $0`
+
+log () {
+	echo 1>&2 "$@"
+	return 0
+}
+
+Config=$1
+if [ "$Config" = "" ]; then
+	log "usage: ${Program} <config>"
+	exit 1
+fi
+
+#
+# Check if the configuration directory exists.  Make sure that the
+# necessary files can be found, such as amanda.conf and tapelist.
+#
+if [ ! -d ${ConfigDir}/${Config} ]; then
+	log "${Program}: configuration directory ${ConfigDir}/${Config} does not exist."
+	exit 1
+fi
+(cd ${ConfigDir}/${Config} >/dev/null 2>&1) || exit $?
+cd ${ConfigDir}/${Config}
+if [ ! -r amanda.conf ]; then
+	log "${Program}: amanda.conf not found or is not readable in ${ConfigDir}."
+	exit 1
+fi
+
+# Get the location and name of the tapelist filename.  If tapelist is not
+# specified in the amanda.conf file, then use tapelist in the config
+# directory.
+TapeList=`getconf${SUF} tapelist`
+if [ ! "$TapeList" ]; then
+	TapeList="$ConfigDir/$Config/tapelist"
+fi
+if [ ! -r $TapeList ]; then
+	log "${Program}: $TapeList not found or is not readable."
+	exit 1
+fi
+
+Amadmin=$sbindir/amadmin$SUF
+
+[ ! -x $Amadmin ] \
+	&& echo "$Amadmin not found or not executable" >&2 \
 	&& exit 1
 
-TAPELIST=$CONFIG_DIR/$CONFIG/tapelist
-
-[ ! -f $TAPELIST ] \
-	&& echo "$TAPELIST not found" >&2 \
-	&& exit 1
-
-AMADMIN=$sbindir/amadmin$SUF
-
-[ ! -x $AMADMIN ] \
-	&& echo "$AMADMIN not found or not executable" >&2 \
-	&& exit 1
-
-$AMADMIN $CONFIG export \
+$Amadmin $Config export \
 	| grep "^stats: " \
 	| while read LINE; do
 		[ "$LINE" = "" ] && continue
@@ -41,9 +75,9 @@ $AMADMIN $CONFIG export \
 	done \
 	| sort -u \
 	| while read TAPE; do
-		grep " $TAPE\$" $TAPELIST 2>/dev/null >/dev/null
+		grep " $TAPE\$" $TapeList 2>/dev/null >/dev/null
 		[ $? != 0 ] \
-			&& echo "Tape $TAPE missing in $TAPELIST"
+			&& echo "Tape $TAPE missing in $TapeList"
 	done
 
 echo "Ready."
diff --git a/server-src/amfreetapes.sh.in b/server-src/amfreetapes.sh.in
--- a/server-src/amfreetapes.sh.in
+++ b/server-src/amfreetapes.sh.in
@@ -4,42 +4,83 @@
 #
 
 prefix=@prefix@
+exec_prefix=@exec_prefix@
+sbindir=@sbindir@
+libexecdir=@libexecdir@
 
-CONFIG=$1
+ConfigDir=@CONFIG_DIR@
+
+PATH=$libexecdir:$sbindir:/usr/bin:/bin:/usr/sbin:/sbin:/usr/ucb
+export PATH
+
+Program=`basename $0`
+
+log () {
+	echo 1>&2 "$@"
+	return 0
+}
+
+Config=$1
+if [ "$Config" = "" ]; then
+	log "usage: ${Program} <config> <volume header>"
+	exit 1
+fi
 VOLHEADER=$2
-[ "$CONFIG" = "" ] && CONFIG=icem
-[ "$VOLHEADER" = "" ] && VOLHEADER=VOL
+if [ "$VOLHEADER" = "" ]; then
+	log "usage: ${Program} <config> <volume header>"
+	exit 1
+fi
 
-AMETC=@CONFIG_DIR@/$CONFIG
+#
+# Check if the configuration directory exists.  Make sure that the
+# necessary files can be found, such as amanda.conf and tapelist.
+#
+if [ ! -d ${ConfigDir}/${Config} ]; then
+	log "${Program}: configuration directory ${ConfigDir}/${Config} does not exist."
+	exit 1
+fi
+(cd ${ConfigDir}/${Config} >/dev/null 2>&1) || exit $?
+cd ${ConfigDir}/${Config}
+if [ ! -r amanda.conf ]; then
+	log "${Program}: amanda.conf not found or is not readable in ${ConfigDir}."
+	exit 1
+fi
 
-TAPELIST=$AMETC/tapelist
-ALLTAPELIST=$AMETC/tapelist.all
+# Get the location and name of the tapelist filename.  If tapelist is not
+# specified in the amanda.conf file, then use tapelist in the config
+# directory.
+TapeList=`getconf${SUF} tapelist`
+if [ ! "$TapeList" ]; then
+	TapeList="$ConfigDir/$Config/tapelist"
+fi
+if [ ! -r $TapeList ]; then
+	log "${Program}: $TapeList not found or is not readable."
+	exit 1
+fi
 
-[ ! -f $TAPELIST ] \
-	&& echo "no tapelist $TAPELIST found" >&2 \
-	&& exit 1
+AllTapeList="${TapeList}.all"
 
-[ ! -f $ALLTAPELIST ] \
-	&& echo "no tapelist $ALLTAPELIST found" >&2 \
-	&& cat $TAPELIST | sed 's/^.* //' | sort -u > $ALLTAPELIST \
-	&& echo "$ALLTAPELIST created" >&2
+[ ! -f $AllTapeList ] \
+	&& echo "no tapelist $AllTapeList found" >&2 \
+	&& cat $TapeList | sed 's/^.* //' | sort -u > $AllTapeList \
+	&& echo "$AllTapeList created" >&2
 
-cat $TAPELIST | sed 's/^.* //' > $ALLTAPELIST.n
-cat $ALLTAPELIST >> $ALLTAPELIST.n
-sort -u $ALLTAPELIST.n > $ALLTAPELIST && rm -f $ALLTAPELIST.n
+cat $TapeList | sed 's/^.* //' > $AllTapeList.n
+cat $AllTapeList >> $AllTapeList.n
+sort -u $AllTapeList.n > $AllTapeList && rm -f $AllTapeList.n
 
-MAXTAPE=`cat $ALLTAPELIST | sed "s/^$VOLHEADER//" | sort -n | tail -1`
+MAXTAPE=`cat $AllTapeList | sed "s/^$VOLHEADER//" | sort -n | tail -1`
 NEXTTAPE=`expr $MAXTAPE + 1`
 echo "last Tape is ${VOLHEADER}${MAXTAPE}" >&2
 
 I=1
 while [ $I -le $MAXTAPE ]; do
-	WRITTEN=`grep "${VOLHEADER}${I}\$" $TAPELIST`
-	EXISTS=`grep "${VOLHEADER}${I}\$" $ALLTAPELIST`
+	WRITTEN=`grep "${VOLHEADER}${I}\$" $TapeList`
+	EXISTS=`grep "${VOLHEADER}${I}\$" $AllTapeList`
 	if [ "$EXISTS" = "" -a "$WRITTEN" = "" ]; then
 		echo "missing tape ${VOLHEADER}${I}" >&2
-		echo "${VOLHEADER}${I}" >> $ALLTAPELIST \
-		&& echo "added ${VOLHEADER}${I} to $ALLTAPELIST" >&2
+		echo "${VOLHEADER}${I}" >> $AllTapeList \
+		&& echo "added ${VOLHEADER}${I} to $AllTapeList" >&2
 	elif [ "$EXISTS" = "" -a "$WRITTEN" != "" ]; then
 		echo "tape written, but not existing: ${VOLHEADER}${I}" >&2
 	elif [ "$EXISTS" != "" -a "$WRITTEN" = "" ]; then
